plugins {
    id 'maven-publish'
    id 'idea'
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'maven-publish'
    apply plugin: 'idea'

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
    }

    repositories {
        maven {
            name = "Jared's maven"
            url = "https://maven.blamejared.com/"
        }
        maven {
            name = "ModMaven"
            url = "https://modmaven.dev"
        }
        maven {
            name = "CurseForge Maven"
            url = "https://cursemaven.com"
            content {
                includeGroup "curse.maven"
            }
        }
    }

    sourceSets.main.resources {
        srcDir('src/generated/resources')

        exclude("**/*.bbmodel")
        exclude("src/generated/**/.cache")
    }

    java.toolchain.languageVersion = JavaLanguageVersion.of(21)

    publishing {
        publications {
            register('mavenJava', MavenPublication) {
                from components.java
            }
        }
        repositories {
            maven {
                url "file://${project.projectDir}/repo"
            }
        }
    }

    idea {
        module {
            downloadSources = true
            downloadJavadoc = true
        }
    }
}
